In [1]:
import movielens_dataset
import pandas as pd

In [2]:
movielens_dataset.download_imdb_data_25m()

,title,genres_ml,year,imdb_id,writer,actor,director,producer,actress,cinematographer,...,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres_imdb,directors,writers
movie_id,,,,,,,,,,,,,,,,,,,,,
1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,tt0114709,nm0169505|nm0230032|nm0004056|nm0710020|nm0923736,nm0000158|nm0000741|nm0725543|nm0001815,nm0005124,\N,\N,\N,...,movie,Toy Story,Toy Story,0,1995,\N,81,Adventure|Animation|Comedy,nm0005124,nm0005124|nm0230032|nm0004056|nm0710020|nm0923...
2,Jumanji,Adventure|Children|Fantasy,1995,tt0113497,nm0378144|nm0852430|nm0833164|nm0885575,nm0000245|nm0404993,nm0002653,nm0472256,nm0000379|nm0001372,\N,...,movie,Jumanji,Jumanji,0,1995,\N,104,Adventure|Comedy|Family,nm0002653,nm0378144|nm0852430|nm0833164|nm0885575
3,Grumpier Old Men,Comedy|Romance,1995,tt0113228,nm0425756,nm0000527|nm0000493,nm0222043,nm0075828|nm0204862,nm0000268|nm0000047,nm0005714,...,movie,Grumpier Old Men,Grumpier Old Men,0,1995,\N,101,Comedy|Romance,nm0222043,nm0425756
4,Waiting to Exhale,Comedy|Drama|Romance,1995,tt0114885,nm0573334|nm0060103,\N,nm0001845,nm0771834|nm0842470,nm0001365|nm0000291|nm0222643|nm0005375,\N,...,movie,Waiting to Exhale,Waiting to Exhale,0,1995,\N,124,Comedy|Drama|Romance,nm0001845,nm0573334|nm0060103
5,Father of the Bride Part II,Comedy,1995,tt0113041,nm0352443|nm0329304|nm0583600,nm0000188|nm0001737,nm0796124,\N,nm0000473|nm0931090,nm0204567,...,movie,Father of the Bride Part II,Father of the Bride Part II,0,1995,\N,106,Comedy|Family|Romance,nm0796124,nm0352443|nm0329304|nm0583600|nm0796124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209157,We,Drama,2018,tt6671244,nm1818234,nm9400914|nm7904438,nm1415482,nm1761379,nm9547544|nm9560986,nm6845015,...,movie,Wij,Wij,0,2018,\N,100,Drama,nm1415482,nm1415482|nm1818234
209159,Window of the Soul,Documentary,2001,tt0297986,\N,\N,nm1065588|nm0142504,nm0848542,\N,\N,...,movie,Window of the Soul,Janela da Alma,0,2001,\N,73,Documentary,nm0142504|nm1065588,nm0142504|nm1065588
209163,Bad Poems,Comedy|Drama,2018,tt6755366,\N,nm2520391|nm0468514,\N,nm2726042,nm6331240|nm0847744,nm3006351|nm2803658,...,movie,Bad Poems,Rossz versek,0,2018,\N,97,Comedy|Drama,nm2520391,nm2520391
209169,A Girl Thing,(no genres listed),2001,tt0249603,\N,\N,nm0003022,nm0076184,nm0001009|nm0000330|nm0000360|nm0001201,nm0002423,...,tvMovie,A Girl Thing,A Girl Thing,0,2001,\N,237,Comedy|Drama|Romance,nm0003022,nm0003022
209171,Women of Devil's Island,Action|Adventure|Drama,1962,tt0055323,nm0002759,nm0022663|nm0534972|nm0612219,nm0659992,\N,nm0580440|nm0709424|nm0068952,nm0068882,...,movie,Women of Devil's Island,Le prigioniere dell'isola del diavolo,0,1962,\N,86,Action|Adventure|Drama,nm0659992,nm0002759|nm0659992

In [2]:
movies_df = movielens_dataset.items_df('ml-1m')
movies_df

,title,genres,year,original_title,imdb_id,synopsis,summary,image_url,description,item_id,image_slug
movie_id,,,,,,,,,,,
1,Toy Story,"[Animation, Children's, Comedy]",1995,NaN,tt0114709,A boy called Andy Davis (voice: John Morris) u...,A cowboy doll is profoundly threatened and jea...,https://m.media-amazon.com/images/M/MV5BMDU2ZW...,A cowboy doll is profoundly threatened and jea...,1,[1]
2,Jumanji,"[Adventure, Children's, Fantasy]",1995,NaN,tt0113497,The film begins in 1869 in the town of Brantfo...,When two kids find and play a magical board ga...,https://m.media-amazon.com/images/M/MV5BZTk2Zm...,When two kids find and play a magical board ga...,2,[2]
3,Grumpier Old Men,"[Comedy, Romance]",1995,NaN,tt0113228,None,John and Max resolve to save their beloved bai...,https://m.media-amazon.com/images/M/MV5BMjQxM2...,John and Max resolve to save their beloved bai...,3,[3]
4,Waiting to Exhale,"[Comedy, Drama]",1995,NaN,tt0114885,None,"Based on Terry McMillan's novel, this film fol...",https://m.media-amazon.com/images/M/MV5BYzcyMD...,"Based on Terry McMillan's novel, this film fol...",4,[4]
5,Father of the Bride Part II,[Comedy],1995,NaN,tt0113041,NaN,George Banks must deal not only with his daugh...,https://m.media-amazon.com/images/M/MV5BOTEyNz...,George Banks must deal not only with his daugh...,5,[5]
...,...,...,...,...,...,...,...,...,...,...,...
3948,Meet the Parents,[Comedy],2000,NaN,tt0212338,None,Male nurse Greg Focker meets his girlfriend's ...,https://m.media-amazon.com/images/M/MV5BMGNlMG...,Male nurse Greg Focker meets his girlfriend's ...,3948,[3948]
3949,Requiem for a Dream,[Drama],2000,NaN,tt0180093,Harry Goldfarb (Jared Leto) and Tyrone Love (M...,The drug-induced utopias of four Coney Island ...,https://m.media-amazon.com/images/M/MV5BOTdiNz...,The drug-induced utopias of four Coney Island ...,3949,[3949]
3950,Tigerland,[Drama],2000,NaN,tt0170691,"At Fort Polk, Louisiana, in September of 1971,...",A group of recruits go through Advanced Infant...,https://m.media-amazon.com/images/M/MV5BMDNjYT...,A group of recruits go through Advanced Infant...,3950,[3950]
3951,Two Family House,[Drama],2000,NaN,tt0202641,None,A dreamer finds that his wife and friends are ...,https://m.media-amazon.com/images/M/MV5BN2JkZj...,A dreamer finds that his wife and friends are ...,3951,[3951]
3952,"Contender, The","[Drama, Thriller]",2000,NaN,tt0208874,None,Senator Laine Hanson is a contender for U.S. V...,https://m.media-amazon.com/images/M/MV5BYTIzYT...,Senator Laine Hanson is a contender for U.S. V...,3952,[3952]

In [5]:
movies_df['description'].isna().value_counts(normalize=True)

False    0.995879
True     0.004121
Name: description, dtype: float64

In [58]:
movies_df['image_slug'].apply(len).value_counts(normalize=True) * 100

1    99.573875
0     0.426125
Name: image_slug, dtype: float64

In [6]:
reviews_df = movielens_dataset.reviews_df('ml-25m')
reviews_df

          user_id  item_id  rating           timestamp
0               1      296     5.0 2006-05-17 15:34:04
1               1      306     3.5 2006-05-17 12:26:57
2               1      307     5.0 2006-05-17 12:27:08
3               1      665     5.0 2006-05-17 15:13:40
4               1      899     3.5 2006-05-17 12:21:50
...           ...      ...     ...                 ...
25000090   162541    50872     4.5 2009-04-28 21:16:12
25000091   162541    55768     2.5 2009-04-28 20:53:18
25000092   162541    56176     2.0 2009-04-28 20:31:37
25000093   162541    58559     4.0 2009-04-28 21:17:14
25000094   162541    63876     5.0 2009-04-28 21:01:55

[25000095 rows x 4 columns]

In [73]:
len(reviews_df) / (reviews_df['item_id'].nunique() * reviews_df['user_id'].nunique())

0.002604839052572928